version: '3.3'
services:
    kola:
      build: .
      ports:
       - "8050:8050" 
      env_file:
      - ./.env

    db:
      image: postgres:13-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASS}
        - POSTGRES_DB=${POSTGRES_DB}
      ports:
        - "5432:5432"

volumes:
  postgres_data: